services:
  db:
    image: mariadb:10.11
    restart: always  # always вместо unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - laravel_network
    command: --default-authentication-plugin=mysql_native_password

  app:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile.prod  # отдельный Dockerfile для prod
    restart: always
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: false
    volumes:
      - ./app:/var/www
      - ./.env:/var/www/.env:ro
      - storage_data:/var/www/storage
      - session_data:/var/www/storage/framework/sessions
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db
    networks:
      - laravel_network
    command: php-fpm

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"        # HTTP
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - logs_nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

volumes:
  mysql_data_prod:
  storage_data:
  session_data:
  logs_nginx:
  redis_data:

networks:
  laravel_network:
    driver: bridge